############# English navigation ##############

# main menu
[[main]]
name = "Inicio"
pageRef = "/"
weight = 1

[[main]]
name = "Sobre"
pageRef = "/about"
weight = 2


# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1
